name: CI
on: [push]
jobs:

  build-lnx-tst:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: env/setup
      run: env/setup.sh
    - name: git submodule status
      id: git-submodule-status
      run: echo "::set-output name=hash::$(git submodule status | sed -e 's/^.\([^ ]*\) \([^ ]*\).*/\2 \1/' | LANG=C sort | openssl sha1 -binary | xxd -p -c20)"
    - uses: actions/cache@v2
      with:
        path: .git/modules
        key: git-modules-${{ steps.git-submodule-status.outputs.hash }}
    - name: git submodule
      run: env/submodule.sh --jobs 3

    - name: make Linux dashboard
      run: debug=crossndk make -j3 -C tst-network
